### ISSUE TITLE
🐛 0-width size progress bar

### ISSUE THREAD

**Issue by Sigmanificient** [frannuaire/progress-bar#1]
The component doesn't follow any size constraints, thus, using a CSS property such as `place-items: center` or the parent element can to the progress bar to render as a zero width box.

![image](https://user-images.githubusercontent.com/53050011/143291773-b527b18e-24ce-454e-9fe3-de45bc3ae503.png)

## Reproduce the bug

```html
<div class="bug-demo__parent">
    <progress-bar data-progress="40"></progress-bar>
</div>
```

```css
.bug-demo__parent {
    width: 100vw;
    display: grid;
    place-items: center;
}
```
